### PR TITLE
small changes to the schema (no changes to structure)

### PR DESCRIPTION
**Pull request by wingechr**
* removed "null" types. Reason: this is already implied by fields not being mandatory

* added titles, formats, option(hidden=true), readonly.
  These do not affect validation in any way but are usefull to the editor on the platform

### CODE REVIEW

**Comment by Ludee** [comment]
The test are failing and there are merge conflicts. 
Is this connected to #40?

**Comment by Ludee** [comment]
How do we proceed with this PR? Will it be included in the v1.5 release?

**Comment by wingechr** [comment]
ich schau mirs an

**Comment by chrwm** [comment]
@wingechr, all right, I'll wait for your cue.

**Comment by jh-RLI** [comment]
@wingechr I think it makes no sense to remove the null types, since we explicitly recommend (see [20.7 in the table](https://github.com/OpenEnergyPlatform/oemetadata/blob/release/oemetadata15/metadata/latest/metadata_key_description.md)) the use of null types if there is no value for a field. Would you agree with that?

**Comment by jh-RLI** [comment]
The tests fail because there are `null` values in the [example.json](https://github.com/OpenEnergyPlatform/oemetadata/blob/feature/improve_schema_1_4_0/metadata/v140/example.json).

**Comment by jh-RLI** [comment]
I have adapted the changes to schema.json (added the new key "title") for version 1.5.0. The changes to the types I have omitted, as described in my last comment. The changes are now in the PR #56 . I will leave this branch open until the discussion is finished.

**Comment by jh-RLI** [comment]
As the changes are already part of #56 i will close this PR down. The reason why the ci fails is documented in #65

**Pull request closed without merging**
