### PR TITLE
Release v2.0.0 Halloween Special 🎃🍭🍬🍾

### LINKED ISSUE #197: Release - Major Version - 2.0.0 - Refactor OEMetadata for NFDI
## Description of the release

The update to _frictionless Data Package 2.0_ and a needed conceptual change of the metadata schema was the impetus for an update to the next major version. Up to version 1.6.0, the OEM metadata was customised to individual database tables or files. All keys only describe the entire collection. This has been fixed in the latest version by moving all metadata sections to the resource level. This corresponds to the structure of _DCAT-AP_ and enables the implementation of a collection function on the OEP.
For an improved building and maintaining process, the repo has been updated with a segmented JSON schema and corresponding scripts to generate templates and examples. In addition, the badges have been updated.
Several new keys have been introduced:
- collection / description
- resource / topics 
- resource / embargoPeriod / (start, end, isActive)
- resource / context / title
- resource / context / publisher
- resource / spatial / location / (address, @id, longitude, longitude)
- resource / spatial / extent / (name, @id, resolutionValue, resolutionUnit, boundingBox, crs)
- resource / sources / (authors, publicationYear)
- resource / sources / licenses / copyrightStatement
- resource / licenses / copyrightStatement
- resource / contributors / (path, organization, roles)
- resource / type
- resource / schema / fields / nullable

## Details of the release

**Name:** **Refactor OEMetadata for NFDI**
**Git tag:** v2.0.0 "OEMetadata Major Release v2.0.0"
**Release Manager:** @Ludee 
**Date:** 31.10.2024

## Workflow checklist
- [x] I am aware of the workflow in [RELEASE_PROCEDURE.md](https://github.com/OpenEnergyPlatform/oemetadata/blob/production/RELEASE_PROCEDURE.md)
- [x] 4. 🐙 Create a `Draft GitHub Release`
- [x] 5. 💠 Create a `release` branch
- [x] 6. 📝 Update the version files (CHANGELOG.md, CITATION.cff)
- [x] 7. 🐙 Create a Release Pull Request
- [x] 8. 💠 Set the `Git Tag`
- [x] 9. 🐙 Publish `GitHub Release`
- [x] 10. 💻 Update the documentation
- [x] 11. 🐙 Set up new development

### PR DESCRIPTION
**Pull request by Ludee**
Closes #197

### CODE REVIEW

**Review by jh-RLI — APPROVED** [review]
In general, this seems fine. As we discussed you must move the content from v20 to latest directory (replace everything in latest) and then there is a bit of a struggle to update the paths/urls in the example to ".../latest/..." instead of ".../v20/..."

🎃

**Review by christian-rli — APPROVED** [review]
✅

**Comment by jh-RLI** [comment]
Ah i forgot to mention that you also have to move the tests.

**Comment by jh-RLI** [comment]
i can do that

**Pull request merged**
