### PR TITLE
oemetadata 1.5.0 release

### LINKED ISSUE #41: Handling of unknown or non-existent values missing in metadata description
In the Metadata Description (https://github.com/OpenEnergyPlatform/metadata/wiki/Metadata-Description) information is missing how you proceed if values are either 

- unknown or 
- unknown but existent or 
- not applicable

### LINKED ISSUE #52: OEM needs JSON-LD extension to support linking OEO entities
Linking to entities in OEO should be supported by oemetadata. It is not clear how this is done best. 

It is nice to have the discussion public for later reference and also to have it in one place. Since this is intended to end up in the metadata string, I suggest discussing and making changes in this issue, rather than at the [original LOD-GEOSS location](https://github.com/LOD-GEOSS/databus-snippets/commit/53a401ffe438e9e8b0d825d65ff7245c47347d7e). 

I added file originally commited by @yum-yab . Feel free to make changes in the opened branch add new files and so on. We can clean up the branch before merging or restart with a tidy branch later.

### LINKED ISSUE #60: Create an example table to showcase sound metadata
An example table could be sensible to demonstrate the usefulness of metadata for data contextualisation. It could be provided as a best-practice example and linked in the documentation for new users. If implemented, new users would have a reference example and better guidance in working with metadata.

### PR DESCRIPTION
**Pull request by chrwm**
Working on oemetadata release v1.5.
Create a pull request once all tasks from [release project](https://github.com/OpenEnergyPlatform/oemetadata/projects/2) are addressed.

The following issues will be closed by this PR:
closes #60 
closes #52 
closes #41

This PR also reintroduces the automated tests (CI) for this repository. For this purpose, the test platform was switched from travis ci to github actions. The test procedure is defined in the corresponding configuration file: oemetadata/.github/workflows/metadata-test.yml

### CODE REVIEW

**Comment by jh-RLI** [comment]
Please add changes to the CHANGELOG.md file @chrwm

**Comment by jh-RLI** [comment]
why there ist still a future folder with the json-ld data? I think it would be better to rename the folder to linked data or something similar.

**Comment by jh-RLI** [comment]
Aside from the two questions from above, the PR looks good. I will start updating the test for version 1.5. When everything is ready the relase can be finished and finally the pip package can be updated.

**Comment by chrwm** [comment]
Hi @jh-RLI, I addressed your two points above.

**Comment by Ludee** [comment]
I found several small issues that need to be improved:

- [ ] the corresponding example table on the OEP (create table, delete existing, update links)
- [ ] the README.md should contain the version highlights
- [ ] folder latest/jsonld has an wind example
- [ ] folder name schema/draft07 unclear
- [ ] create a version folder for 1.5

The example metadata needs improvement
- [ ] remove tabs, only spaces
- [ ] exchange context with LOD-GEOSS project
- [ ] add contributors
- [ ] fix parsing error

**Review by Ludee — APPROVED** [review]
I included all suggestions as documented below. Only minor issues were fixed, most in the example file.

**Comment by Ludee** [comment]
I also checked the old version and fixed the broken links

**Comment by Ludee** [comment]
Only open issue is the `draft07` folder in `metaschema`

**Comment by jh-RLI** [comment]
> Only open issue is the `draft07` folder in `metaschema`

this folder respectively the files are used to validate a schema. See the [documentation](http://json-schema.org/specification.html). The name `draft07 `  stands for the used version of the metaschema. In fact, there is already a more recent version.

**Comment by jh-RLI** [comment]
@Ludee  
The folder `v150`: 
From my point of view the data are now double in the repository. in the folder latest is the version v1.5.0. the structure was designed so that the historical version is always stored as a folder with the version and the current version in the latest folder.

**Review by jh-RLI — APPROVED** [review]
@chrwm @Ludee this PR LGTM :) 
if you are done with your changes i will now finish the release and update the pip package.

**Pull request merged**
